app:
  name: "ComfyUI Upscale"
  info: "Upscale ảnh bằng workflow ComfyUI"
  info_link: "https://www.youtube.com/@hungdiffusion"
  themes: "default"
  primary_hue: "emerald"

input:
  image:
    ui:
      type: "image"
      img_type: "pil"
      label: "Ảnh đầu vào"
      height: 600
      container: true
    id: "298-inputs-image"

output:
  image:
    ui:
      type: "image"
      label: "Ảnh upscale"
      format: "png"
      height: 600
      container: true
    id: "34"

server:
  address: "127.0.0.1:8188"
  comfy_folder: "/content/ComfyUI"
