app:
  name: "ComfyUI Image Adjust"
  info: "Điều chỉnh saturation ảnh qua workflow ComfyUI"
  info_link: "https://www.youtube.com/@hungdiffusion"
  themes: "default"
  primary_hue: "emerald"

input:
  image:
    ui:
      type: "image"
      img_type: "pil"
      label: "Ảnh đầu vào"
      height: 600
      container: true
    id: "10-inputs-image"
  saturation:
    ui:
      type: "slider"
      label: "Saturation"
      minimum: -100
      maximum: 100
      value: 0
      step: 1
    id: "11-inputs-saturation"
output:
  image:
    ui:
      type: "image"
      label: "Ảnh kết quả"
      format: "png"
      height: 600
      container: true
    id: "12"

server:
  address: "127.0.0.1:8188"
  comfy_folder: "/content/ComfyUI"
