import { useCallback, useMemo } from "react";

export function useWorkspaceModals({
  setSettingsOpen,
  setInfoOpen,
  setSettingsTab,
  settingsOpen,
  settingsTab,
  theme,
  setTheme,
  themeMenuOpen,
  setThemeMenuOpen,
  selectedThemeOption,
  mainFont,
  setMainFont,
  languagePreference,
  setLanguagePreference,
  healthStatus,
  showServerDetails,
  setShowServerDetails,
  notifyEnabled,
  setNotifyEnabled,
  comfyAddress,
  setComfyAddress,
  serverAddress,
  discovery,
  discoveryLoading,
  discoverySystem,
  discoveryDevice,
  serverDetailRows,
  formatBytes,
  getServers,
  addServer,
  removeServer,
  addServerOpen,
  setAddServerOpen,
  rhSettings,
  updateRhSettings,
  handleRhTestConnection,
  rhTesting,
  rhTestResult,
  rhAccount,
  rhAccountLoading,
  rhAccountError,
  handleRhAccountRefresh,
  rhTokenAccounts,
  rhTotalCoins,
  setRhTestResult,
  setRhAccount,
  setRhAccountError,
  canvasSmartGuide,
  setCanvasSmartGuide,
  canvasSnapGrid,
  setCanvasSnapGrid,
  canvasSnapGridSize,
  setCanvasSnapGridSize,
  maxHistoryDisplay,
  setMaxHistoryDisplay
}) {
  const openSettings = useCallback((tab) => {
    setInfoOpen(false);
    if (tab) setSettingsTab(tab);
    setSettingsOpen(true);
  }, [setInfoOpen, setSettingsOpen, setSettingsTab]);

  const toggleSettings = useCallback(() => {
    setInfoOpen(false);
    setSettingsOpen(current => !current);
  }, [setInfoOpen, setSettingsOpen]);

  const openInfo = useCallback(() => {
    setSettingsOpen(false);
    setInfoOpen(true);
  }, [setInfoOpen, setSettingsOpen]);

  const closeSettings = useCallback(() => setSettingsOpen(false), [setSettingsOpen]);
  const closeInfo = useCallback(() => setInfoOpen(false), [setInfoOpen]);

  const settingsModalProviderValue = useMemo(() => ({
    open: settingsOpen,
    onClose: closeSettings,
    settingsTab,
    setSettingsTab,
    theme,
    setTheme,
    themeMenuOpen,
    setThemeMenuOpen,
    selectedThemeOption,
    mainFont,
    setMainFont,
    languagePreference,
    setLanguagePreference,
    healthStatus,
    showServerDetails,
    setShowServerDetails,
    notifyEnabled,
    setNotifyEnabled,
    comfyAddress,
    setComfyAddress,
    serverAddress,
    discovery,
    discoveryLoading,
    discoverySystem,
    discoveryDevice,
    serverDetailRows,
    formatBytes,
    getServers,
    addServer,
    removeServer,
    addServerOpen,
    setAddServerOpen,
    rhSettings,
    updateRhSettings,
    handleRhTestConnection,
    rhTesting,
    rhTestResult,
    rhAccount,
    rhAccountLoading,
    rhAccountError,
    handleRhAccountRefresh,
    rhTokenAccounts,
    rhTotalCoins,
    setRhTestResult,
    setRhAccount,
    setRhAccountError,
    canvasSmartGuide,
    setCanvasSmartGuide,
    canvasSnapGrid,
    setCanvasSnapGrid,
    canvasSnapGridSize,
    setCanvasSnapGridSize,
    maxHistoryDisplay,
    setMaxHistoryDisplay
  }), [
    addServer,
    addServerOpen,
    canvasSmartGuide,
    canvasSnapGrid,
    canvasSnapGridSize,
    closeSettings,
    comfyAddress,
    discovery,
    discoveryDevice,
    discoveryLoading,
    discoverySystem,
    formatBytes,
    getServers,
    handleRhAccountRefresh,
    handleRhTestConnection,
    healthStatus,
    languagePreference,
    mainFont,
    maxHistoryDisplay,
    notifyEnabled,
    removeServer,
    rhAccount,
    rhAccountError,
    rhAccountLoading,
    rhSettings,
    rhTestResult,
    rhTesting,
    rhTokenAccounts,
    rhTotalCoins,
    selectedThemeOption,
    serverAddress,
    serverDetailRows,
    setAddServerOpen,
    setCanvasSmartGuide,
    setCanvasSnapGrid,
    setCanvasSnapGridSize,
    setComfyAddress,
    setLanguagePreference,
    setMainFont,
    setMaxHistoryDisplay,
    setNotifyEnabled,
    setRhAccount,
    setRhAccountError,
    setRhTestResult,
    setSettingsTab,
    setShowServerDetails,
    setTheme,
    setThemeMenuOpen,
    settingsOpen,
    settingsTab,
    showServerDetails,
    theme,
    themeMenuOpen,
    updateRhSettings
  ]);

  return {
    openSettings,
    toggleSettings,
    openInfo,
    closeSettings,
    closeInfo,
    settingsModalProviderValue
  };
}
